### PR TITLE
CRR - Friendship v2 - Social Media APP

### PR DESCRIPTION
**Pull request by kevcap**
## This project was implemented with the following features:
- [x] Send and receive friend requests
- [x] Add new row to table
- [x] Filtered user posts
- [x] Tests with capybara and rspec
- [x] CSS validation with rubocop

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Invalid ⚠

You have not followed proper Git flow. 
Your PR should be from `feature` to `development`, not directly to `master`.

Please rectify this and submit another review.

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job so far :+1: 
All of the tests are passing :test_tube: 
Let's cover some of the details together :arrow_down: 

### README

- [ ]  Please add **test instructions** :blush: 

### ERD

- [ ]  Since every **like** belongs to a user, **we expect to see that relationship with a line in the diagram**. Currently, there is no line connection between the User model and the Like model.

- [ ]  Friendships table has two foreign keys and both of them are referring to the User. For this reason, **we expect to see two lines that are connecting the User model and the Friendship model**. Currently, there is only one line.

- [ ]  [OPTIONAL] :bulb: Naming convention in **Rails** => if you are referring to the **self id**, you don't have to put the model's name at the beginning of the `id` column name. E.g => in the **users** table, **id** of a specific user is written like `id`, but not `user_id`. If we are in the **invitations** table and want to refer a user with its **id**, then we can use that model prefix as `user_id`. This way you can easily differentiate the columns at one look. 

- [ ]  FK => means **Foreign Key**. Currently, all the columns that are not PK(Primary Key) are signed as FK. Please fix that, you don't have to specify anything unless it is an FK or PK.

- [ ]  Post model => the **content is missing**.

### That's it :blush: After doing the changes, you can request another review.

With all my respect... :pray:

**Comment by kevcap** [comment]
Hello TSE. I do appreciate your comments, and I'll consider doing those changes, but as you can see, this is the **Friendship v2**. The de milestone 1 (elaborating one ERD) already got approved weeks ago.

**Review by trekab — CHANGES_REQUESTED** [review]
## Changes Required: :recycle: 
Hi @kevincappuccino! Well done with this milestone so far. However, there are some requirements I'd like you to look into before moving forward. These are:
- [ ] when friendship/invitation is confirmed, an additional row with reversed user-friend pair is created in your `invitations` table. I have noticed that your table still has one entry after a friendship has been confirmed.
- [ ] __[Note]__ Implementing the above requirement will make finding a user's friends easier since you would just refer to the `user_id` in the invitations table. This introduces opportunities for you to refactor some part of your code e.g. getting posts written by a user and the user's friends.
- [ ] __[Optional]__ Read about `n+1` and make sure there are no `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by kubilaycaglayan** [comment]
> Hello TSE. I do appreciate your comments, and I'll consider doing those changes, but as you can see, this is the **Friendship v2**. The de milestone 1 (elaborating one ERD) already got approved weeks ago.

I am terribly sorry for the confusion :hand_over_mouth: , I will make sure that this will not happen again. 
Please let me know if I can help you in any way if I caused any time lost to you.

With all my respect :pray:

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Kevin Alves Lazaro** 
Great job with the improvements for your project :muscle:  :muscle:  
We still need to fix some details:

- [x] You should have a friendship model which save each couple of users who are friends
- [x] In your friendship model create a confirm_friend method 
- [x] For this project you should create two rows in your database for each friendship
- [x] THe first row is created when friendship is requeted, the seconds one when friendship is accepted
- [x] in the second row to exchange the ids of the 'user_id' and 'friend_id' fields
- [x] Your friendship model has a "confirmed" field, this attribute must be "false" when a friendship is requested and "true" when friendship is accepted.
- [x] Wherever possible, simplify the different queries of your project using the new structure of friendship model (e.g. to get the posts of user friends).

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by kevcap** [comment]
- [x] I just implemented those required changes as you can see ⤵ 😁
image
**Note: instead of _friendship_ I used _invitation_ model, with sent, received invitations, and it's relation.**

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi @kevincappuccino ! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
**** 
_P.S. The photo in your readme isn't working! Please fix this_ 😄 
 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
